converted:
    file:
        charset: GBK
management:
    endpoints:
        web:
            exposure:
                include: '*'
media: mp3,mp4,flv,rmvb
# jodconverter
jodconverter:
    local:
        enabled: true
        #开启openoffice进程对应的端口
        port-numbers: 8100
office:
    home: C:/Program Files (x86)/OpenOffice 4
server:
    port: 7055
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
simText: txt,html,xml,java,properties,sql,log
spring:
    application:
        name: jodconverter
    aop:
        auto: false
        proxy-target-class: false
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    data:
        redis:
            database: 8
            host: localhost
            port: 6379
            username: default
            password: '12345678'
            ssl:
                enabled: false
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    max-wait: -1
                    min-idle: 1
            repositories:
                enabled: false
    datasource:
        hikari:
            y9-public:
                driverClassName: com.mysql.cj.jdbc.Driver
                jdbcUrl: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: '12345678'
                maximumPoolSize: 20
                minimumIdle: 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batchSize: 100
                showSql: true
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 1000MB
    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:///d:/y9config/
y9:
    systemName: jodconverter
    internalIp: 192.168.x.x,10.161.x.x,10.1.x.x,172.20.x.x
    common:
        jodconverterBaseUrl: https://vue.youshengyun.com/jodconverter
    feature:
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity.jpa
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        mongo:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryTenant: net.risesoft.repository
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey: 
            #publicKey: 
            rest:
                fileManagerUrl: http://localhost:8080/fileManager
            ftp:
                host: localhost
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true