MobPush:
    appKey: 2fcd5e3a22ff8
    masterSecret: a1b1325012cd9ba86d48f02332e62bf6
flowable:
    common:
        app:
            idm-url: http://localhost:7056/processAdmin
            tenantId: ""
            idmAdmin:
                user: admin
                password: 111111
logging:
    config: classpath:log4j2.xml
management:
    endpoints:
        web:
            exposure:
                include: '*'
mybatis:
    mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /processAdmin
        register-default-servlet: true
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: processAdmin
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: dev
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: ${NACOS_PASSWORD:111111}
            discovery:
                enabled: false
    config:
        import:
            - optional:nacos:processAdmin.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    data:
        redis:
            database: 8
            host: localhost
            port: 6379
            username: default
            password: '12345678'
            ssl:
                enabled: false
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    max-wait: -1
                    min-idle: 1
            repositories:
                enabled: false
    datasource:
        hikari:
            tenantDefault: spring.datasource.hikari.flowable
            y9-public:
                driverClassName: com.mysql.cj.jdbc.Driver
                jdbcUrl: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: '12345678'
                maximumPoolSize: 20
                minimumIdle: 1
            flowable:
                driverClassName: com.mysql.cj.jdbc.Driver
                jdbcUrl: jdbc:mysql://127.0.0.1:3306/y9_flowable?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: '12345678'
                maximumPoolSize: 20
                minimumIdle: 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batchSize: 100
                showSql: true
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9processAdmin-server
    liquibase:
        change-log: classpath:db/liquibase-changelog.xml
        enabled: true
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 1000MB
y9:
    systemName: processAdmin
    app:
        processAdmin:
            cooperationStateSwitch: false
            dataCenterSwitch: false
            entrustSwitch: true
            messagePushSwitch: false
            pushSwitch: false
            smsSwitch: false
            systemCnName: 流程管理器
            systemName: processAdmin
            todoSwitch: false
            weiXinSwitch: false
            weiXinUrl: https://www.youshengyun.com/Youshengyun/Api/pushTempMessage
            imageCountUrl: http://localhost:8081/imageCount
    service:
        itemAdmin:
            directUrl: http://localhost:7056
        datacenter:
            directUrl: http://localhost:7056
        sms:
            directUrl: http://localhost:7056
        todo:
            directUrl: http://localhost:7056
        msgRemind:
            directUrl: http://localhost:7056
        org:
            directUrl: http://localhost:7055
    common:
        cacheEnabled: true
        kafkaEnabled: true
        orgBaseUrl: http://localhost:7055/platform
        processAdminBaseUrl: http://localhost:7056/processAdmin
        itemAdminBaseUrl: http://localhost:7056/itemAdmin
        datacenterBaseUrl: http://localhost:7056/datacenter
        msgRemindBaseUrl: http://localhost:7056/msgRemind
        smsBaseUrl: http://localhost:7056/sms
        todoBaseUrl: http://localhost:7056/todo
        logBaseUrl: http://localhost:7056/log
        userOnlineBaseUrl: http://localhost:7056/userOnline
    feature:
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        log:
            enabled: true
            # kafka, api
            logSaveTarget: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - https://vue.youshengyun.com:8443
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://127.0.0.1:7056
                    - http://localhost:17056
                    - http://127.0.0.1:17056
            xss:
                ignoreParam:
                    - json_xml
        oauth2:
            resource:
                enabled: true
                saveLogMessage: false
                saveOnlineMessage: false
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*,/editor/*,/modeler*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
                    profile-uri: http://localhost:7055/sso/oauth2.0/profile
